### ISSUE TITLE
Remove photo thumbnail for quotes

### ISSUE THREAD

**Issue by shansul26** [vitac215/capstone-website#2]
The photos are kind of unnecessary, especially since they are not of the people who said what we are quoting.

<img width="638" alt="screen shot 2017-07-26 at 5 29 09 pm" src="https://user-images.githubusercontent.com/3934225/28644585-2d238df8-7228-11e7-8161-db9d302b40a1.png">

**Comment by vitac215** [comment]
fixed. need to update the quote tho
